### ISSUE TITLE
slicing within the same element yields incorrect results

### ISSUE THREAD

**Issue by JorySchossau** [onecodex/nim-bitarray#3]
These fail for small slices:
`import bitarray`
`var ba = create_bitarray(64)`
`ba[0] = true`
`ba[1] = true`
`ba[2] = true`
`ba[7] = true`
`assert ba[0..4] == 7`
`assert ba[2..4] == 1`

**Comment by boydgreenfield** [comment]
@JorySchossau – obviously haven't been using that functionality... so many thanks for the catch and fix! Do you want to submit a PR? In testing your code out here I have one together, but please open and happy to merge from you if you'd prefer.

Otherwise, I'll merge in my new PR (#4) in a day or so and bump the version release. Thanks again!

**Comment by JorySchossau** [comment]
Hi Nick,

This is my first github contribution, so I'm figuring this out. Thanks for
giving me the opportunity to finish the PR!

 - Jory

**Comment by boydgreenfield** [comment]
No problem! Thanks for flagging this.
